.openfinContextPublisher_js_metadata <- function() {
deps_metadata <- list(`openfin_context_publisher` = structure(list(name = "openfin_context_publisher",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-OpenfinContextPublisher.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "openfinContextPublisher",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`openfin_context_publisher` = structure(list(name = "openfin_context_publisher",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-OpenfinContextPublisher.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "openfinContextPublisher",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`openfin_context_publisher` = structure(list(name = "openfin_context_publisher",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'openfin_context_publisher.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "openfinContextPublisher",
all_files = FALSE), class = "html_dependency"),
`openfin_context_publisher` = structure(list(name = "openfin_context_publisher",
version = "0.0.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'openfin_context_publisher.min.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "openfinContextPublisher",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"))
return(deps_metadata)
}
